### ISSUE TITLE
OpenAPI docs for project API endpoints

### ISSUE THREAD

**Issue by tmthecoder** [GTBitsOfGood/juno#75]
# OpenAPI docs for user API endpoints

## Context

We want to provide user documentation for the project API Endpoints

## Acceptance Criteria

- Documentation is available for all `/project/` endpoints and contains appropriate parameter, precondition, and return info
- Use this guide (has a linked GitHub example): https://docs.nestjs.com/openapi/introduction

## Testing

- N/A

**Comment by UZ9** [comment]
Encountered bug: creating a project with a duplicate ID results in status code 500 ALREADY_EXISTS: The resource already exists.
