### ISSUE TITLE
API Gateway JWT Generation Tests

### ISSUE THREAD

**Issue by tmthecoder** [GTBitsOfGood/juno#93]
# Write Tests for JWT Generation (api-gateway)

## Context

The API Gateway exposes a JWT Generation endpoint that generates tokens that users use for their main form of auth across services. We need to test this endpoint to make sure it works as intended

## Requirements & Criteria

- [x] Tests are written within `api-gateway/tests/auth.e2e-spec.ts` 
- [x] Tests cover cases of invalid input (with appropriate exception/error checking)
- [x] Tests cover cases of correct input

NOTE: The full test-suite for any package can be run **in the root directory** of the project by running `yarn test:e2e:[service-name]`

**Comment by UZ9** [comment]
Closed by #97
